# Generated by Django 6.0.4 on 2026-04-25 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('year', 'Год'), ('month', 'Месяц')], max_length=10, verbose_name='Тип периода')),
                ('measure_type', models.CharField(choices=[('books', 'Книги'), ('pages', 'Страницы')], max_length=10, verbose_name='Единица измерения')),
                ('target', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Целевое значение')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['-period_start'],
            },
        ),
    ]
