# Generated by Django 6.0.4 on 2026-04-25 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст цитаты')),
                ('page_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сессии')),
                ('pages_read', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Прочитано страниц')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('total_pages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество страниц')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='Обложка')),
                ('published_year', models.IntegerField(blank=True, null=True, verbose_name='Год публикации')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний ID')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='books.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'Хочу прочитать'), ('reading', 'Читаю'), ('finished', 'Прочитал'), ('dropped', 'Не буду дочитывать')], default='want_to_read', max_length=20, verbose_name='Статус')),
                ('current_page', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущая страница')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1–5)')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Дата начала чтения')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата окончания чтения')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Книга пользователя',
                'verbose_name_plural': 'Книги пользователей',
            },
        ),
    ]
